### ISSUE TITLE
Copying my game

### ISSUE THREAD

**Issue by codergautam** [AldoRmzCode/wargardenz.io#2]
Hi, this is a blatant copy of my game swordbattle.io, at least give me some credit :)

https://github.com/codergautam/swordbattle.io

**Comment by AldoRmzCode** [comment]
Hiii !, it's not in production yet, but I'll give you the credits right
now, thank you very much :)
sorry for the delay

**Comment by AldoRmzCode** [comment]
hi, it's not in production yet, but I'll give you the credits right now, thank you very much :)
sorry for the delay and for the inconvenience

**Comment by AldoRmzCode** [comment]
again I apologize, and I have already given you the deserved credits, if you need anything else just let me know.
I will continue to make more changes.

**Comment by codergautam** [comment]
ok np
